services:
  - type: web
    name: django-todo-app
    env: "python"
    buildCommand: "pip install -r requirements.txt"
    startCommand: |
      python manage.py migrate &&
      gunicorn taskproject.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: taskproject.settings
      - key: PYTHON_VERSION
        value: 3.12.4
